#include <gtest/gtest.h>

#include <stdexcept>

#include "rest/SymbolMap.h"

using namespace hyperliquid;

TEST(SymbolMapTest, ResolvesExactIdItWasAddedWith)
{
    SymbolMap map;
    map.add("ETH", 4);
    EXPECT_EQ(map.resolve("ETH"), 4);
}

TEST(SymbolMapTest, UnknownSymbolThrows)
{
    SymbolMap map;
    map.add("ETH", 4);
    EXPECT_THROW(map.resolve("BTC"), std::invalid_argument);
}

TEST(SymbolMapTest, ResolvingOnEmptyMapThrows)
{
    SymbolMap map;
    EXPECT_THROW(map.resolve("ETH"), std::invalid_argument);
}

TEST(SymbolMapTest, SymbolLookupIsCaseSensitive)
{
    SymbolMap map;
    map.add("ETH", 4);
    EXPECT_THROW(map.resolve("eth"), std::invalid_argument);
}

TEST(SymbolMapTest, FirstAddWinsOnDuplicateSymbol)
{
    // unordered_map::insert used by SymbolMap::add keeps the first mapping and
    // silently ignores later ones for the same key.
    SymbolMap map;
    map.add("ETH", 4);
    map.add("ETH", 999);
    EXPECT_EQ(map.resolve("ETH"), 4);
}

// --- Asset-id range scheme mirrored from ExchangeRequestBuilder::initializeMapping ---
//
// Perp assets (default meta universe): raw index, e.g. 0, 1, 2, ...
// Spot pairs (spotMetaAndAssetCtxs): 10000 + <pair's position in meta.universe>. This is
// keyed by *pair* position, not a token's own `index` field - those are different numbering
// spaces, since one token can be the base of many pairs. Only canonical (single, token/USDC)
// pairs also get their bare token name (e.g. "PURR") mapped as a convenience alias.
// Dex-scoped perp assets (per-dex meta): 100000 + perpIdx * 10000 + index,
// where perpIdx is the 1-based position of the dex in perpDexs().dexes.

TEST(SymbolMapTest, PerpAssetsUseRawUniverseIndex)
{
    SymbolMap map;
    map.add("BTC", 0);
    map.add("ETH", 1);
    map.add("SOL", 2);

    EXPECT_EQ(map.resolve("BTC"), 0);
    EXPECT_EQ(map.resolve("ETH"), 1);
    EXPECT_EQ(map.resolve("SOL"), 2);
}

TEST(SymbolMapTest, SpotPairsAreOffsetByTenThousand)
{
    SymbolMap map;
    // Canonical pair positions 0 and 1 in spotMeta().universe, same numbering as perp
    // indices, but must not collide with perp asset ids once offset.
    map.add("PURR", 0 + 10000);
    map.add("HFUN", 1 + 10000);

    EXPECT_EQ(map.resolve("PURR"), 10000);
    EXPECT_EQ(map.resolve("HFUN"), 10001);
}

TEST(SymbolMapTest, NonCanonicalSpotPairIsKeyedByPairPositionNotBaseTokenIndex)
{
    SymbolMap map;
    // A token's own `index` (e.g. 1105 for a base token) is unrelated to its pair's
    // position in the universe list (e.g. 907) - only the latter is a valid asset id.
    map.add("@907", 907 + 10000);

    EXPECT_EQ(map.resolve("@907"), 10907);
    EXPECT_THROW(map.resolve("HYPE"), std::invalid_argument);
}

TEST(SymbolMapTest, AutoGeneratedPairNameIsRemappedToPairPositionNotItsOwnIndexField)
{
    // spotMeta().universe[i].name for auto-generated pairs is "@<pair.index>", which is a
    // *different* number from the pair's array position i - e.g. the pair at position 907
    // can be named "@1035" while some unrelated pair at a different position is named
    // "@907". initializeMapping must key the symbol map by position ("@<i>"), matching the
    // "coin" identifier l2Book/assetCtxs use, not the pair's own decorative name field.
    SymbolMap map;
    int pairIndex = 907;
    std::string autoGeneratedName = "@1035"; // this pair's own `index` field, irrelevant here
    bool isAutoGeneratedName = !autoGeneratedName.empty() && autoGeneratedName[0] == '@';
    map.add(isAutoGeneratedName ? ("@" + std::to_string(pairIndex)) : autoGeneratedName, pairIndex + 10000);

    EXPECT_EQ(map.resolve("@907"), 10907);
    EXPECT_THROW(map.resolve("@1035"), std::invalid_argument);
}

TEST(SymbolMapTest, PerpAndSpotIdsDoNotCollide)
{
    SymbolMap map;
    map.add("BTC", 0);        // perp asset index 0
    map.add("SOMECOIN", 0 + 10000); // spot pair position 0

    EXPECT_EQ(map.resolve("BTC"), 0);
    EXPECT_EQ(map.resolve("SOMECOIN"), 10000);
}

TEST(SymbolMapTest, DexScopedPerpAssetsUsePerpIdxFormula)
{
    SymbolMap map;
    // First builder-dex (perpIdx = 1), two assets at index 0 and 1.
    int perpIdx = 1;
    map.add("DEX1-A", 100000 + (perpIdx * 10000) + 0);
    map.add("DEX1-B", 100000 + (perpIdx * 10000) + 1);

    // Second builder-dex (perpIdx = 2), asset at index 0.
    perpIdx = 2;
    map.add("DEX2-A", 100000 + (perpIdx * 10000) + 0);

    EXPECT_EQ(map.resolve("DEX1-A"), 110000);
    EXPECT_EQ(map.resolve("DEX1-B"), 110001);
    EXPECT_EQ(map.resolve("DEX2-A"), 120000);
}

TEST(SymbolMapTest, DexScopedIdsDoNotCollideWithPerpOrSpot)
{
    SymbolMap map;
    map.add("BTC", 0);
    map.add("PURR", 10000);
    map.add("DEX1-A", 100000 + (1 * 10000) + 0);

    EXPECT_EQ(map.resolve("BTC"), 0);
    EXPECT_EQ(map.resolve("PURR"), 10000);
    EXPECT_EQ(map.resolve("DEX1-A"), 110000);
}
